# Generated by Django 6.0.2 on 2026-02-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма платежа")),
                ("session_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="Id сессии")),
                ("link", models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата обучения",
            },
        ),
    ]
