# Generated by Django 6.0.2 on 2026-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="link",
            new_name="checkout_url",
        ),
        migrations.RemoveField(
            model_name="price",
            name="amount",
        ),
        migrations.AddField(
            model_name="price",
            name="stripe_price_id",
            field=models.CharField(default=0, max_length=100, verbose_name="ID цены в Stripe"),
            preserve_default=False,
        ),
    ]
