# Generated by Django 6.0.2 on 2026-02-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_course_price_course_stripe_price_id_and_more"),
        ("users", "0007_rename_link_price_checkout_url_remove_price_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="lms.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
