# Generated by Django 6.0.2 on 2026-02-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_price_course_price_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="checkout_url",
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name="Ссылка на оплату"),
        ),
    ]
