# Generated by Django 6.0.1 on 2026-01-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(max_length=1000, verbose_name="Описания")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Картинка")),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(max_length=1000, verbose_name="Описания")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Картинка")),
                ("video_url", models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ["title"],
            },
        ),
    ]
