# Generated by Django 5.2.12 on 2026-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(max_length=1000, verbose_name="Описания")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Картинка")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Стоимость курса"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания курса")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления курса")),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="ID цены Stripe"),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CourseSubscription",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(max_length=1000, verbose_name="Описания")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Картинка")),
                ("video_url", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Стоимость урока"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания урока")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления урока")),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="ID цены Stripe"),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ["title"],
            },
        ),
    ]
