# Generated by Django 6.0.2 on 2026-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_lesson_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Стоимость курса"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID цены Stripe"),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Стоимость урока"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID цены Stripe"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID продукта Stripe"),
        ),
    ]
